"""empty message

Revision ID: dc8cb26ed786
Revises: 
Create Date: 2017-01-13 12:43:24.698791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8cb26ed786'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('street_address_1', sa.String(length=100), nullable=True),
    sa.Column('street_address_2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('call_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('headline', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('list_start_datetime', sa.DateTime(), nullable=True),
    sa.Column('list_end_datetime', sa.DateTime(), nullable=True),
    sa.Column('target_phone_number', sa.String(length=10), nullable=True),
    sa.Column('target_name', sa.String(length=100), nullable=True),
    sa.Column('target_official_type', sa.String(length=100), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('talking_point_1', sa.String(length=70), nullable=True),
    sa.Column('talking_point_2', sa.String(length=70), nullable=True),
    sa.Column('talking_point_3', sa.String(length=70), nullable=True),
    sa.Column('kudos_text', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('headline', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('list_start_datetime', sa.DateTime(), nullable=True),
    sa.Column('list_end_datetime', sa.DateTime(), nullable=True),
    sa.Column('target_email', sa.String(length=255), nullable=True),
    sa.Column('target_name', sa.String(length=100), nullable=True),
    sa.Column('target_official_type', sa.String(length=60), nullable=True),
    sa.Column('email_subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('kudos_text', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('headline', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('list_start_datetime', sa.DateTime(), nullable=True),
    sa.Column('list_end_datetime', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('event_start_datetime', sa.DateTime(), nullable=True),
    sa.Column('event_end_datetime', sa.DateTime(), nullable=True),
    sa.Column('kudos_text', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_actions')
    op.drop_table('email_actions')
    op.drop_table('call_actions')
    op.drop_table('users')
    # ### end Alembic commands ###
